from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime


class UploadResponseDTO(BaseModel):
    id: str = Field(..., description="The unique UUID of the file record")
    filename: str = Field(..., description="The original name of the uploaded file")
    file_path: str = Field(
        ..., description="The server's internal storage path or public URL of the file"
    )
    file_type: str = Field(
        ..., description="The MIME type of the file (e.g., image/jpeg, image/png)"
    )
    file_size: str = Field(
        ..., description="The human-readable formatted file size (e.g., '142.5 KB')"
    )
    user_id: str = Field(
        ..., description="The unique identifier of the user who owns this file"
    )
    created_at: Optional[datetime] = Field(
        None, description="Timestamp when the file was initially uploaded"
    )
    updated_at: Optional[datetime] = Field(
        None, description="Timestamp when the file metadata was last updated"
    )

    class Config:
        from_attributes = True


class UploadMetaUpdateDTO(BaseModel):
    filename: Optional[str] = Field(
        None,
        min_length=1,
        max_length=255,
        description="The updated display name for the file",
    )
    description: Optional[str] = Field(
        None, max_length=500, description="Additional notes or metadata for this file"
    )


class AntiSpoofingReportDTO(BaseModel):
    is_live: bool = Field(
        ...,
        description="True if the face is evaluated as real/genuine, False if it is a spoof attack",
    )
    confidence_score: Optional[float] = Field(
        None,
        description="The accuracy confidence score generated by the AI model (0.0 - 1.0)",
    )
    attack_type: Optional[str] = Field(
        None,
        description="The detected spoofing vector (e.g., '2D Print Attack', 'Replay Screen Attack', 'None')",
    )
    evaluated_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp when the biometric scan occurred",
    )


class BulkUploadResponseDTO(BaseModel):
    success_count: int = Field(
        ..., description="Number of files successfully processed and saved"
    )
    failures_count: int = Field(
        ...,
        description="Number of files rejected due to validation or spoofing failures",
    )
    uploaded_files: List[UploadResponseDTO] = Field(
        default=[], description="List of successful file metadata profiles"
    )
